/**
 * Shared audio-generation core.
 *
 * Backs the audio-mode chat tools (`design_voice`, `clone_voice`,
 * `generate_speech`, `generate_music`). Each provider speaks a completely
 * different API, so the backend is selected by `ModelConfig.provider`.
 *
 * Currently implemented:
 *   - minimax — https://api.minimaxi.com
 *       voice design   → POST /v1/voice_design
 *       voice clone     → POST /v1/files/upload  + POST /v1/voice_clone
 *       text-to-speech  → POST /v1/t2a_v2
 *       music           → POST /v1/music_generation
 *
 * All synthesized audio is returned as a base64 string + MIME type so callers
 * can persist it via the C++ `write_file` RPC (binary mode).
 */

import { bridgeRPC, getAudioModels, type ModelConfig } from '@/bridge'
import { getAudioMime, invalidateAsset } from '@/lib/assets'
import { devProxiedFetch } from '@/lib/dev-proxy'

/** Default speech-synthesis model used when the audio model has none set. */
const DEFAULT_SPEECH_MODEL = 'speech-2.5-hd-preview'
/** Default music-generation model. */
const DEFAULT_MUSIC_MODEL = 'music-2.6'

// ─── Public types ──────────────────────────────────────────────────

export interface AudioResult {
  success: boolean
  /** Base64-encoded audio bytes (no data-URL prefix). */
  audioBase64?: string
  /** MIME type of the audio (e.g. "audio/mpeg"). */
  mime?: string
  /** Voice id produced by a design/clone call. */
  voiceId?: string
  error?: string
}

export interface DesignVoiceOptions {
  /** Natural-language description of the target voice. */
  prompt: string
  /** Short text spoken in the returned preview audio (≤ 500 chars). */
  previewText: string
  /** Optional custom voice id; otherwise one is generated by the provider. */
  voiceId?: string
  model?: ModelConfig
}

export interface CloneVoiceOptions {
  /** res:// path of the reference audio (mp3/m4a/wav, 10s–5min, ≤ 20MB). */
  referenceAudio: string
  /** Custom voice id to assign to the cloned voice. */
  voiceId: string
  /** Optional text to synthesize a preview and activate the cloned voice. */
  previewText?: string
  /** Speech model used for the preview synthesis. */
  speechModel?: string
  model?: ModelConfig
}

export interface SpeechOptions {
  text: string
  voiceId: string
  /** Speed 0.5–2.0 (default 1.0). */
  speed?: number
  /** Volume 0–10 (default 1.0). */
  volume?: number
  /** Pitch -12–12 (default 0). */
  pitch?: number
  /** Emotion tag (e.g. "happy", "sad", "angry"). */
  emotion?: string
  /** Override the speech model. */
  speechModel?: string
  model?: ModelConfig
}

export interface MusicOptions {
  /** Style / mood / scenario description (≤ 2000 chars). */
  prompt: string
  /** Lyrics with optional structure tags ([Verse]/[Chorus]); ≤ 3500 chars. */
  lyrics?: string
  /** Generate instrumental music with no vocals. */
  instrumental?: boolean
  /** Let the model auto-write lyrics from the prompt. */
  lyricsOptimizer?: boolean
  /** Override the music model. */
  musicModel?: string
  model?: ModelConfig
}

// ─── Shared helpers ────────────────────────────────────────────────

function authHeaders(model: ModelConfig): HeadersInit {
  if (model.authMode === 'none') return {}
  return { Authorization: `Bearer ${model.apiKey.trim()}` }
}

function endpointBase(model: ModelConfig): string {
  return model.apiEndpoint.trim().replace(/\/+$/, '')
}

/** Append the provider group id (MiniMax GroupId) as a query param if present. */
function withGroup(url: string, model: ModelConfig): string {
  if (!model.groupId) return url
  return `${url}${url.includes('?') ? '&' : '?'}GroupId=${encodeURIComponent(model.groupId)}`
}

/** Decode a hex audio string into a base64 string (in chunks, for big files). */
function hexToBase64(hex: string): string {
  const clean = hex.trim().replace(/[^0-9a-fA-F]/g, '')
  const len = Math.floor(clean.length / 2)
  const bytes = new Uint8Array(len)
  for (let i = 0; i < len; i++) {
    bytes[i] = parseInt(clean.substr(i * 2, 2), 16)
  }
  let binary = ''
  const CHUNK = 0x8000
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK))
  }
  return btoa(binary)
}

function base64ToBlob(b64: string, mime: string): Blob {
  const bin = atob(b64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return new Blob([bytes], { type: mime })
}

function fileNameOf(path: string): string {
  return path.split('/').pop() || 'audio.mp3'
}

/** Read MiniMax `base_resp` and turn a non-zero status into an error string. */
function minimaxError(json: any): string | undefined {
  const resp = json?.base_resp
  if (resp && typeof resp.status_code === 'number' && resp.status_code !== 0) {
    return `MiniMax error ${resp.status_code}: ${resp.status_msg ?? 'unknown'}`
  }
  return undefined
}

function resolveModel(opt?: ModelConfig): ModelConfig | undefined {
  return opt ?? getAudioModels()[0]
}

function ensureUsable(model?: ModelConfig): string | undefined {
  if (!model || !model.apiEndpoint) {
    return 'No audio model configured. Add one in Settings → Audio Models.'
  }
  if (model.authMode !== 'none' && !model.apiKey) {
    return 'Audio model has no API Key configured.'
  }
  return undefined
}

// ─── MiniMax backend ───────────────────────────────────────────────

async function minimaxDesignVoice(opt: DesignVoiceOptions, model: ModelConfig): Promise<AudioResult> {
  const base = endpointBase(model)
  const body: Record<string, unknown> = {
    prompt: opt.prompt,
    preview_text: opt.previewText.slice(0, 500),
  }
  if (opt.voiceId) body.voice_id = opt.voiceId

  const resp = await devProxiedFetch(withGroup(`${base}/v1/voice_design`, model), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...authHeaders(model) },
    body: JSON.stringify(body),
  })
  const json = await resp.json()
  const err = minimaxError(json)
  if (err) return { success: false, error: err }
  if (!json.trial_audio || !json.voice_id) {
    return { success: false, error: 'voice_design returned no audio/voice_id' }
  }
  return {
    success: true,
    voiceId: json.voice_id,
    audioBase64: hexToBase64(json.trial_audio),
    mime: 'audio/mpeg',
  }
}

async function minimaxSynthesize(opt: SpeechOptions, model: ModelConfig): Promise<AudioResult> {
  const base = endpointBase(model)
  const voiceSetting: Record<string, unknown> = { voice_id: opt.voiceId }
  if (opt.speed != null) voiceSetting.speed = opt.speed
  if (opt.volume != null) voiceSetting.vol = opt.volume
  if (opt.pitch != null) voiceSetting.pitch = opt.pitch
  if (opt.emotion) voiceSetting.emotion = opt.emotion

  const body = {
    model: opt.speechModel || model.model || DEFAULT_SPEECH_MODEL,
    text: opt.text,
    stream: false,
    voice_setting: voiceSetting,
    audio_setting: { sample_rate: 32000, bitrate: 128000, format: 'mp3', channel: 1 },
  }

  const resp = await devProxiedFetch(withGroup(`${base}/v1/t2a_v2`, model), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...authHeaders(model) },
    body: JSON.stringify(body),
  })
  const json = await resp.json()
  const err = minimaxError(json)
  if (err) return { success: false, error: err }
  const hex = json?.data?.audio
  if (!hex) return { success: false, error: 't2a_v2 returned no audio' }
  return { success: true, audioBase64: hexToBase64(hex), mime: 'audio/mpeg' }
}

async function minimaxCloneVoice(opt: CloneVoiceOptions, model: ModelConfig): Promise<AudioResult> {
  const base = endpointBase(model)

  // 1. Upload the reference audio → file_id.
  const refB64 = await bridgeRPC('read_file', { path: opt.referenceAudio, binary: true })
  const form = new FormData()
  form.append('purpose', 'voice_clone')
  form.append('file', base64ToBlob(refB64, getAudioMime(opt.referenceAudio)), fileNameOf(opt.referenceAudio))

  const uploadResp = await devProxiedFetch(withGroup(`${base}/v1/files/upload`, model), {
    method: 'POST',
    headers: authHeaders(model),
    body: form,
  })
  const uploadJson = await uploadResp.json()
  const uploadErr = minimaxError(uploadJson)
  if (uploadErr) return { success: false, error: uploadErr }
  const fileId = uploadJson?.file?.file_id ?? uploadJson?.file_id
  if (!fileId) return { success: false, error: 'file upload returned no file_id' }

  // 2. Clone the voice.
  const cloneBody: Record<string, unknown> = {
    file_id: fileId,
    voice_id: opt.voiceId,
    model: opt.speechModel || model.model || DEFAULT_SPEECH_MODEL,
  }
  const cloneResp = await devProxiedFetch(withGroup(`${base}/v1/voice_clone`, model), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...authHeaders(model) },
    body: JSON.stringify(cloneBody),
  })
  const cloneJson = await cloneResp.json()
  const cloneErr = minimaxError(cloneJson)
  if (cloneErr) return { success: false, error: cloneErr }

  // 3. Synthesize a preview (also "activates" the temporary cloned voice).
  if (opt.previewText) {
    const preview = await minimaxSynthesize(
      { text: opt.previewText, voiceId: opt.voiceId, speechModel: opt.speechModel, model },
      model,
    )
    if (preview.success) {
      return { ...preview, voiceId: opt.voiceId }
    }
    return { success: true, voiceId: opt.voiceId, error: preview.error }
  }
  return { success: true, voiceId: opt.voiceId }
}

async function minimaxMusic(opt: MusicOptions, model: ModelConfig): Promise<AudioResult> {
  const base = endpointBase(model)
  const body: Record<string, unknown> = {
    model: opt.musicModel || DEFAULT_MUSIC_MODEL,
    prompt: opt.prompt,
    output_format: 'hex',
    audio_setting: { sample_rate: 44100, bitrate: 256000, format: 'mp3' },
  }
  if (opt.lyrics) body.lyrics = opt.lyrics
  if (opt.instrumental) body.is_instrumental = true
  if (opt.lyricsOptimizer) body.lyrics_optimizer = true

  const resp = await devProxiedFetch(withGroup(`${base}/v1/music_generation`, model), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...authHeaders(model) },
    body: JSON.stringify(body),
  })
  const json = await resp.json()
  const err = minimaxError(json)
  if (err) return { success: false, error: err }
  const hex = json?.data?.audio
  if (!hex) return { success: false, error: 'music_generation returned no audio' }
  return { success: true, audioBase64: hexToBase64(hex), mime: 'audio/mpeg' }
}

// ─── Provider dispatch ─────────────────────────────────────────────

function unsupported(provider: string | undefined): AudioResult {
  return {
    success: false,
    error: `Unsupported audio provider "${provider ?? 'unknown'}". Only "minimax" is implemented.`,
  }
}

export async function designVoice(opt: DesignVoiceOptions): Promise<AudioResult> {
  const model = resolveModel(opt.model)
  const bad = ensureUsable(model)
  if (bad) return { success: false, error: bad }
  if ((model!.provider ?? 'minimax') !== 'minimax') return unsupported(model!.provider)
  try {
    return await minimaxDesignVoice(opt, model!)
  } catch (e) {
    return { success: false, error: `Voice design failed: ${e instanceof Error ? e.message : String(e)}` }
  }
}

export async function cloneVoice(opt: CloneVoiceOptions): Promise<AudioResult> {
  const model = resolveModel(opt.model)
  const bad = ensureUsable(model)
  if (bad) return { success: false, error: bad }
  if ((model!.provider ?? 'minimax') !== 'minimax') return unsupported(model!.provider)
  try {
    return await minimaxCloneVoice(opt, model!)
  } catch (e) {
    return { success: false, error: `Voice clone failed: ${e instanceof Error ? e.message : String(e)}` }
  }
}

export async function synthesizeSpeech(opt: SpeechOptions): Promise<AudioResult> {
  const model = resolveModel(opt.model)
  const bad = ensureUsable(model)
  if (bad) return { success: false, error: bad }
  if ((model!.provider ?? 'minimax') !== 'minimax') return unsupported(model!.provider)
  try {
    return await minimaxSynthesize(opt, model!)
  } catch (e) {
    return { success: false, error: `Speech synthesis failed: ${e instanceof Error ? e.message : String(e)}` }
  }
}

export async function generateMusic(opt: MusicOptions): Promise<AudioResult> {
  const model = resolveModel(opt.model)
  const bad = ensureUsable(model)
  if (bad) return { success: false, error: bad }
  if ((model!.provider ?? 'minimax') !== 'minimax') return unsupported(model!.provider)
  try {
    return await minimaxMusic(opt, model!)
  } catch (e) {
    return { success: false, error: `Music generation failed: ${e instanceof Error ? e.message : String(e)}` }
  }
}

// ─── Persisting audio ──────────────────────────────────────────────

/** Write base64 audio bytes to a res:// path and refresh any cached data URL. */
export async function saveAudioBase64(base64: string, path: string): Promise<string> {
  await bridgeRPC('write_file', { path, content: base64, binary: true })
  invalidateAsset(path)
  return path
}
